Feat/#66 upload external image files using drag and drop
woowacourse-teams/2020-zeze pull request #165
Opened 2020-08-18 07:51 UTC by lowoon

현재 간단하게 외부 파일을 업로드 할 수 있는 api만 만들어 두었습니다.
@ModelAttribute로 요청받는 것을 하나로 통합하여 service내에서 type에 맞게 분기하는 방법이 더 나을지 이야기 해보아야 할 것 같습니다.

2020-08-19 12:22 UTC, kimhodol approved these changes
고생하셨습니다 💯

2020-08-20 05:45 UTC, YerinCho requested changes

2020-08-20 05:45 UTC, YerinCho commented on client/src/components/editor/MarkdownEditor.tsx
> +          uploadUrl = await onDrop?.(new File([buffer], "external"));
로컬파일이랑 외부파일 전부 이 로직 타는 것 같은데 확인 해주세요~ 
두 경우 모두 onDrop이 실행되는게 맞으면 클라이언트/서버 모두 불필요한 코드들 삭제해주세요!

2020-08-20 06:45 UTC, lalize commented on client/src/components/editor/MarkdownEditor.tsx
> +          uploadUrl = await onDrop?.(new File([buffer], "external"));
dataUrl인 경우만 로직을 타고 있어요~~

썸네일은 dataUrl로 되어 있는게 많더라구요~

2020-08-20 08:37 UTC, YerinCho approved these changes

2020-08-20 08:38 UTC, merged