Feat/#151 private public
woowacourse-teams/2020-zeze pull request #170
Opened 2020-08-18 11:20 UTC by YerinCho

resolves #151 

LoginUserIdMethodArgumentResolver 에서 token이 없는경우에 null을 반환하도록 구현된 건 맞는데,,,
String으로 형변환 할 때 null이 "null"로 형변환되어서 로직을 제대로 못타요...
그래서 일단 임시로 대충 바꿔놨는데 저렇게 해도 되는진 잘 모르겠습니다. 😭😭😭

2020-08-19 11:40 UTC, kimhodol approved these changes

2020-08-19 11:40 UTC, kimhodol commented on client/src/api/slide.ts
> +      },
`params: page` 해도 되지 않나요?

2020-08-20 02:39 UTC, jjj0611 reviewed
이건 그냥 사용자 경험 관점에서만의 이야기인데
private public 바꾸는 부분에 대한 api를 하나 뚫어서 변경 시마다 요청을 보내게 하면 어떨까요?
자물쇠 버튼이 변경이 되는 순간 상태가 이미 변경됐다고 느껴져서요!
어떻게 생각하시나요~?

2020-08-20 08:07 UTC, jjj0611 approved these changes

2020-08-20 14:12 UTC, lalize requested changes

2020-08-20 14:12 UTC, lalize commented on client/src/pages/Editor.tsx
> +  }, []);
저장 후 new slides 누르면 이전 내용이 그대로 남아있어요

2020-08-20 14:13 UTC, YerinCho commented on client/src/pages/Editor.tsx
> +  }, []);
오 이게 그런 문제가 있었군요

2020-08-20 14:19 UTC, lalize commented on client/src/pages/Editor.tsx
> +        }
굳이 상태를 트래킹할 필요는 없다고 봐요.

2020-08-20 14:19 UTC, lalize commented on client/src/pages/Editor.tsx
> +
여기서 save 해주면 되지 않을까요?

2020-08-20 14:20 UTC, YerinCho commented on client/src/pages/Editor.tsx
> +
오 안돼요... useState로 관리하고 있어서 렌더링이 되어야 상태가 바뀌더라고요

2020-08-20 14:40 UTC, lalize commented on client/src/pages/Editor.tsx
> +
😭

2020-08-21 02:47 UTC, YerinCho commented on client/src/pages/Editor.tsx
> +        }
상태가 렌더링 이후에 바뀌어서 어쩔수없이 accessLevel 디펜던시 건 useEffect 추가 했어요.
그렇다 보니까 저렇게 되어버렸네요...

2020-08-21 07:01 UTC, merged