Feat/#247 slide number
woowacourse-teams/2020-zeze pull request #248
Opened 2020-09-24 05:10 UTC by YerinCho

resolves #247

2020-10-01 13:28 UTC, kimhodol requested changes
깔끔하네요! 수고하셨습니다.
피드백 남긴거 확인 부탁드려요~

2020-10-01 13:28 UTC, kimhodol commented on client/src/components/markdown/index.tsx
> +  index: number
`index`가 `required`면 `<Markdown>`을 사용하는 여러 곳에서 터지는 현상이 있어요!
`SlideExample`라던가, `Preview`에서 터지는 것 일단 확인했습니다!

예린님도 한 번 확인해주세요 !

2020-10-01 13:28 UTC, kimhodol commented on client/src/components/markdown/index.tsx
> +      {index === 0 ? <></> : <div className="index">{index}</div>}
항상 페이지수를 보이게 하기 보단 metadata에서 `pageNumber: true` 등의 옵션을 줘서 사용자가 선택할 수 있게 해보는건 어떨까요?

2020-10-05 04:54 UTC, YerinCho commented on client/src/components/markdown/index.tsx
> +  index: number
간과한 부분 감사합니다 :)

2020-10-05 09:58 UTC, lalize approved these changes
수고하셨습니다~

2020-10-05 09:58 UTC, lalize commented on client/src/components/markdown/index.tsx
> +      {pageNumberVisible && index !== 0 ? <div className="index">{index}</div> : <></>}
Markdown 컴포넌트가 에디터 화면에서도 사용하는 컴포넌트니 FullScreenMode에서 렌더링하는 건 어떨까요?

2020-10-05 09:58 UTC, lalize commented on client/src/utils/metadata.ts
> +pageNumber: ${pageNumber ?? "true"}
페이지 넘버 표시 여부도 메타데이터로 해야하는 군요.

2020-10-05 10:02 UTC, YerinCho commented on client/src/utils/metadata.ts
> +pageNumber: ${pageNumber ?? "true"}
핀이 ui 이쁘게 만들어주면 메타데이터로 하지 않아도 돼요 ! ㅎㅎ

2020-10-05 10:02 UTC, YerinCho commented on client/src/utils/metadata.ts
> +pageNumber: ${pageNumber ?? "true"}
근데 에디터에 추가하는것과 메타데이터에 추가하는것 뭐가 더 나을지는 모르겠어요...

2020-10-06 04:36 UTC, kimhodol approved these changes
수고하셨습니다 ^_^

2020-10-06 04:37 UTC, merged